[package]
name = "idcurl"
version = "0.1.0"
authors = ["Kalle Samuels <charles@derkarl.org>"]
edition = "2018"
description = "Idiomatic http client over curl"

[dependencies]
curl-sys={version="0.4" }
url="1.7"
http="0.1"
libc="0.2.42"
