[package]
name = "idcurl"
version = "0.1.0"
authors = ["Kalle Samuels <charles@derkarl.org>"]
edition = "2018"
description = "Idiomatic http client over curl"

[dependencies]
curl={version="0.4", path="../curl-rust"}
url="1.7"
http="0.1"
